services:
  - type: web
    name: campscout-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    rootDir: .
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://campscout-demo.surge.sh
      - key: DATABASE_PATH
        value: /opt/render/project/src/campscout.db
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_HOURS
        value: 24
      - key: JWT_REFRESH_TOKEN_EXPIRE_DAYS
        value: 30