name: Deploy CampScout (Minimal)

on:
  push:
    branches: [ main, copilot ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies and fix Rollup
      working-directory: ./frontend
      run: |
        rm -rf package-lock.json node_modules
        npm install --legacy-peer-deps
        npm install @rollup/rollup-linux-x64-gnu --save-dev --legacy-peer-deps
        
    - name: Build application
      working-directory: ./frontend
      run: npm run build
      env:
        VITE_API_URL: https://your-app.onrender.com
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/dist