name: Deploy CampScout (Frontend to GitHub Pages)

on:
  push:
    branches: [ main, copilot ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd frontend
          npm install --legacy-peer-deps

      - name: Build frontend
        run: |
          cd frontend
          VITE_API_URL=https://campscout-up-demo.railway.app npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist