name: Deploy CampScout (PNPM)

on:
  push:
    branches: [ main, copilot ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        cache-dependency-path: './frontend/pnpm-lock.yaml'
    
    - name: Install dependencies
      working-directory: ./frontend
      run: pnpm install --frozen-lockfile || pnpm install
        
    - name: Build application
      working-directory: ./frontend
      run: pnpm build
      env:
        VITE_API_URL: https://campscout-up-demo.railway.app
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/dist