name: Deploy CampScout (macOS)

on:
  push:
    branches: [ main, copilot ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install and Build
      working-directory: ./frontend
      run: |
        npm install --legacy-peer-deps
        npm run build
      env:
        VITE_API_URL: https://campscout-backend-demo.railway.app
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/dist