name: Deploy CampScout with Yarn

on:
  push:
    branches: [ main, copilot ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Enable Corepack
      run: corepack enable
    
    - name: Install dependencies with Yarn
      run: |
        cd frontend
        yarn install --frozen-lockfile || yarn install
        
    - name: Build application
      run: |
        cd frontend
        yarn build
      env:
        VITE_API_URL: https://campscout-up-demo.railway.app
        NODE_ENV: production
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: success()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/dist
        force_orphan: true